name: ai_resume_local

services:
  frontend_cv:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_APP_NODE_ENV: ${NEXT_PUBLIC_APP_NODE_ENV}
    container_name: frontend_cv_app
    # restart: unless-stopped
    env_file:
      - ./.env
    environment:
      NODE_ENV: ${NEXT_PUBLIC_APP_NODE_ENV}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      NEXT_PUBLIC_APP_NODE_ENV: ${NEXT_PUBLIC_APP_NODE_ENV}
    ports:
      - "3100:3100"
