export const JOBSEEKER_ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  JOBS: "/jobs",
  ANALYSIS: "/jobseeker/analysis",
  PROFILE: "/profile",
  CV: "/cv",
  FAVORITES: "/jobseeker/favorites",
  APPLICATIONS: "/jobseeker/applications",
  CVS: "/jobseeker/cvs",
  CHANGE_PASSWORD: "/jobseeker/change-password",
} as const;

export const RECRUITER_ROUTES = {
  HOME: "/recruiter",
  LOGIN: "/recruiter/login",
  REGISTER: "/recruiter/register",
  DASHBOARD: "/recruiter/dashboard",
  JOBS: "/recruiter/jobs",
  APPLICANTS: "/recruiter/applicants",
  ANALYTICS: "/recruiter/analytics",
  CV_ANALYSIS: "/recruiter/cv-analysis",
} as const;

export const ROUTES = {
  HOME: JOBSEEKER_ROUTES.HOME,
  JOBS: JOBSEEKER_ROUTES.JOBS,
  JOB_SEEKER_ANALYSIS: JOBSEEKER_ROUTES.ANALYSIS,
  JOB_SEEKER_LOGIN: JOBSEEKER_ROUTES.LOGIN,
  JOB_SEEKER_REGISTER: JOBSEEKER_ROUTES.REGISTER,
  JOB_SEEKER_PROFILE: JOBSEEKER_ROUTES.PROFILE,
  JOB_SEEKER_CV: JOBSEEKER_ROUTES.CV,
  JOB_SEEKER_FAVORITES: JOBSEEKER_ROUTES.FAVORITES,
  JOB_SEEKER_APPLICATIONS: JOBSEEKER_ROUTES.APPLICATIONS,
  JOB_SEEKER_CVS: JOBSEEKER_ROUTES.CVS,
  JOB_SEEKER_CHANGE_PASSWORD: JOBSEEKER_ROUTES.CHANGE_PASSWORD,
  RECRUITER_HOME: RECRUITER_ROUTES.HOME,
  RECRUITER_DASHBOARD: RECRUITER_ROUTES.DASHBOARD,
  RECRUITER_LOGIN: RECRUITER_ROUTES.LOGIN,
  RECRUITER_REGISTER: RECRUITER_ROUTES.REGISTER,
  RECRUITER_CV_ANALYSIS: RECRUITER_ROUTES.CV_ANALYSIS,
} as const;
